general:
steps:
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '9232a0e6trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
